#!/usr/bin/env python
#
# Copyright 2023 Basislager Services
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

"""Find deleted users.

This script is a Python implementation of Tiak's shell script.
It looks for users who were deleted before the user ID was added to the ranking.
"""

import argparse
import json
import re
import subprocess as sp
import os
import sys


SCRIPTDIR = os.path.dirname(os.path.abspath(__file__))


def main():
    parser = argparse.ArgumentParser()
    parser.parse_args()

    rankingpath = os.path.join(SCRIPTDIR, "..", "ranking", "ranking.json")
    with open(rankingpath) as fp:
        ranking_lines = fp.readlines()

    # Map id -> linenumber
    lines = dict()
    for i, data in enumerate(ranking_lines):
        if r"gel\u00f6schter User" in data:
            userid = re.search(r'"id": (?P<id>[0-9]+)', ranking_lines[i - 1])["id"]
            lines[userid] = i + 1

    for userid, line in lines.items():
        command = ["git", "log", "-1", "-L", f"{line},+1:{rankingpath}", "--pretty="]
        result = sp.run(command, capture_output=True, encoding="utf8")

        match = re.search(r'-\s*"name": "(?P<name>.*?)"', result.stdout)
        if match:
            name = match["name"]
            print(f'"{userid}": "{name}",')
        else:
            print(f'"{userid}": null,')


if __name__ == "__main__":
    sys.exit(main())
