#!/usr/bin/env python
#
# Copyright 2023-2024 Basislager Services
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#



import json
import os

import matplotlib.pyplot as plt

if __name__ == "__main__":
    with open(os.path.join(os.path.dirname(__file__), "..", "postle", "postings.json")) as fp:
        postings = json.load(fp)

    hist = dict()
    for e in postings.values():
        user = e["user"]
        hist[user] = hist.get(user, 0) + 1
    hist = dict(sorted(hist.items(), key=lambda item: item[1], reverse=True))

    xvalues = hist.keys()
    yvalues = hist.values()

    plt.bar(xvalues, yvalues)
    plt.xticks(rotation=45, fontsize=8, ha="right", rotation_mode="anchor")
    plt.tight_layout()
    plt.show()
