#
# Copyright 2021 Basislager Services
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

name: Book
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  book:
    name: 'Generate book and push results'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          curl -o /tmp/chromium-browser.deb             http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_112.0.5615.49-0ubuntu0.18.04.1_amd64.deb
          curl -o /tmp/chromium-browser-l10n.deb        http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser-l10n_112.0.5615.49-0ubuntu0.18.04.1_all.deb
          curl -o /tmp/chromium-codecs-ffmpeg-extra.deb http://archive.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg-extra_112.0.5615.49-0ubuntu0.18.04.1_amd64.deb
          sudo apt -f -y install /tmp/chromium-*.deb
          sudo apt-get install -y \
            curl \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-latex-recommended
          curl -L -o /tmp/pandoc.deb 'https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb'
          sudo dpkg -i /tmp/pandoc.deb
          pip install git+https://github.com/basislagerservices/tickergadse.git

      - name: 'Run book generator for Unsin(n)kable III'
        run: |
          tickergadse-book \
            --ticker-id 2000130527798 \
            --ticker-id 2000133087737 \
            --ticker-id 2000134489588 \
            --ticker-id 2000135886471 \
            --ticker-id 2000137241138 \
            --ticker-id 2000138443314 \
            --ticker-id 2000139914652 \
            --ticker-id 2000141504301 \
            --ticker-id 2000142622431 \
            --ticker-id 2000144473769 \
            --ticker-id 3000000108553 \
            --ticker-id 3000000179807 \
            --ticker-id 3000000186882 \
            --ticker-id 3000000194352 \
            --ticker-id 3000000201552 \
            --ticker-id 3000000209412 \
            --book logbook \
            --output books/unsinnkable.pdf \
            --output books/unsinnkable.epub

      - name: 'Run book generator for Raumschiff Ersterpreis'
        run: |
          tickergadse-book \
            --ticker-id 2000130527798 \
            --ticker-id 2000133087737 \
            --ticker-id 2000134489588 \
            --ticker-id 2000135886471 \
            --ticker-id 2000137241138 \
            --ticker-id 2000138443314 \
            --ticker-id 2000139914652 \
            --ticker-id 2000141504301 \
            --ticker-id 2000142622431 \
            --ticker-id 2000144473769 \
            --ticker-id 3000000108553 \
            --ticker-id 3000000179807 \
            --ticker-id 3000000186882 \
            --ticker-id 3000000194352 \
            --ticker-id 3000000201552 \
            --ticker-id 3000000209412 \
            --book ersterpreis \
            --output books/ersterpreis.pdf \
            --output books/ersterpreis.epub

      - name: 'Commit changes'
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: 'Update books'
          add: 'books'
