#
# Copyright 2021 Basislager Services
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

name: Crawler
on:
  schedule:
    - cron: '30 2,14 * * *'
  workflow_dispatch:

jobs:
  crawler:
    name: 'Run crawler and push results'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: actions/cache@v2
        with:
          path: '~/crawler-state.pickle'
          key: '${{runner.os}}-crawler-state-${{secrets.CACHE_VERSION}}'

      - name: 'Install dependencies'
        run: |
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver
          pip install git+https://github.com/basislagerservices/tickergadse.git

      - name: 'Run crawler'
        run: |
          tickergadse-crawler \
            --once \
            --continue \
            --state-file ~/crawler-state.pickle \
            --output ranking/ranking.json

      - name: 'Commit changes'
        uses: EndBug/add-and-commit@v8
        with:
          author_name: 'Basislager Services'
          author_email: 'services@basislager.fun'
          message: 'Update ranking files'
          add: 'ranking/ranking.json'
